"""Seed and synthetic benchmark dataset for Indian Funding Opportunities (DST, ANRF, CSIR, AICTE, NSP, DBT)."""
from typing import List
from src.schemas.foa import (
    AcademicOntologyTag,
    AgencyType,
    BeneficiaryType,
    Deadlines,
    EligibilityCriteria,
    FinancialCeiling,
    FundingOpportunity,
    ResearchDomain,
)
from datetime import date, datetime, timezone
import hashlib


def get_seed_foa_dataset() -> List[FundingOpportunity]:
    """Returns curated Indian FOAs across all target statutory bodies."""
    raw_data = [
        {
            "foa_id": "DST-CRG-2026-01",
            "title": "DST Core Research Grant (CRG) in Advanced Materials and AI",
            "agency": AgencyType.DST,
            "scheme_name": "Core Research Grant Scheme",
            "source_url": "https://dst.gov.in/call-for-proposals/crg-2026",
            "brief_summary": "Call for research proposals in emerging areas of artificial intelligence, semiconductor materials, clean energy, and quantum technologies. Supports individual PIs and collaborative groups from recognized Indian academic institutions.",
            "thematic_areas": ["Artificial Intelligence", "Semiconductor Materials", "Clean Energy", "Quantum Computing"],
            "domain": ResearchDomain.COMPUTER_SCIENCE_AI,
            "thematic_thrust": "AI for Scientific Discovery and Advanced Materials",
            "target_beneficiary": BeneficiaryType.FACULTY,
            "open_date": date(2026, 7, 1),
            "closing_date": date(2026, 9, 30),
            "extended_closing_date": date(2026, 10, 15),
            "max_amount_inr": 6000000.0,  # 60 Lakhs
            "overhead_pct": 10.0,
            "raw_budget_text": "Maximum financial assistance up to Rs. 60 Lakhs for a duration of 3 years including 10% institutional overheads and equipment budget.",
            "min_qualification": "Ph.D. in Science or Engineering with regular faculty/scientist appointment",
            "max_age_limit": 60,
            "eligible_institutions": ["CFTI", "IIT", "NIT", "IISc", "UGC Recognized Universities", "National Labs"],
            "raw_eligibility_text": "Applicants should hold a regular academic/research position in a recognized Indian academic institution or national laboratory with a Ph.D. degree and at least 3 SCI indexed journal publications.",
            "full_text_content": "DEPARTMENT OF SCIENCE AND TECHNOLOGY (DST)\nCALL FOR PROPOSALS: CORE RESEARCH GRANT (CRG) 2026\n1. Objective: To promote individual-centric competitive research in high-impact national thrust areas including AI, materials, and quantum computing.\n2. Eligibility: The Principal Investigator (PI) must hold a regular faculty position with Ph.D. in Science/Engineering. Age limit is 60 years. Co-PI from industry is welcome but not mandatory.\n3. Budget Ceiling: Maximum funding up to Rs. 60,00,000 (INR 60 Lakhs) over 36 months.\n4. Deadlines: Call opens on 01-07-2026. Proposals must be submitted via the online portal on or before 30-09-2026. Extended deadline: 15-10-2026.\n5. Institution: CFTIs, Central/State Universities, and NAAC Accredited Private Institutions.",
        },
        {
            "foa_id": "ANRF-POWER-2026-03",
            "title": "ANRF Promoting Opportunities for Women in Exploratory Research (POWER) Grant",
            "agency": AgencyType.ANRF,
            "scheme_name": "ANRF POWER Research Grant",
            "source_url": "https://anrfonline.in/schemes/power-2026",
            "brief_summary": "Encouraging emerging women researchers in STEM disciplines to undertake exploratory and breakthrough basic/applied scientific research with dedicated project funding and networking mentorship.",
            "thematic_areas": ["Women in STEM", "Biomedical Devices", "Applied Mathematics", "Chemical Biology", "Robotics"],
            "domain": ResearchDomain.INTERDISCIPLINARY,
            "thematic_thrust": "Empowering Women Scientists in Exploratory STEM Research",
            "target_beneficiary": BeneficiaryType.WOMEN_SCIENTIST,
            "open_date": date(2026, 8, 1),
            "closing_date": date(2026, 10, 31),
            "extended_closing_date": None,
            "max_amount_inr": 3000000.0,  # 30 Lakhs
            "overhead_pct": 12.5,
            "raw_budget_text": "Level I: Rs. 30 Lakhs for 3 years for CFTI/National Lab researchers; Level II: Rs. 25 Lakhs for State/Private universities.",
            "min_qualification": "Ph.D. degree in Science, Engineering or Medicine",
            "max_age_limit": 55,
            "eligible_institutions": ["All Indian Universities and Colleges recognized by UGC/AICTE"],
            "raw_eligibility_text": "Open exclusively to Indian women scientists with regular faculty positions in recognized universities or research laboratories. Must have Ph.D. with at least two publications.",
            "full_text_content": "ANUSANDHAN NATIONAL RESEARCH FOUNDATION (ANRF)\nPOWER RESEARCH GRANTS FOR WOMEN SCIENTISTS 2026\nObjective: To mitigate gender disparity in science and engineering research funding by funding active women scientists.\nFunding Ceiling: Level-1 grants up to Rs. 30,00,000/- for 3 years.\nEligibility: Regular female faculty/researchers aged up to 55 years holding a Ph.D. degree.\nClosing Date: Proposals close on 31 October 2026.",
        },
        {
            "foa_id": "CSIR-EMR-2026-02",
            "title": "CSIR Extra Mural Research (EMR-II) Scheme in Biotechnology & Health Sciences",
            "agency": AgencyType.CSIR,
            "scheme_name": "Extra Mural Research Scheme",
            "source_url": "https://csir.res.in/schemes/emr-2026",
            "brief_summary": "Extramural financial support for sponsored research projects focused on affordable diagnostic devices, molecular therapeutics, bioinformatics pipelines, and infectious disease management.",
            "thematic_areas": ["Biotechnology", "Diagnostics", "Bioinformatics", "Genomics", "Therapeutics"],
            "domain": ResearchDomain.BIOTECHNOLOGY_HEALTHCARE,
            "thematic_thrust": "Translational Biotechnology and Affordable Healthcare Diagnostics",
            "target_beneficiary": BeneficiaryType.FACULTY,
            "open_date": date(2026, 6, 15),
            "closing_date": date(2026, 9, 15),
            "extended_closing_date": date(2026, 9, 30),
            "max_amount_inr": 4500000.0,  # 45 Lakhs
            "stipend_monthly_inr": 37000.0,  # JRF/SRF stipend
            "overhead_pct": 10.0,
            "raw_budget_text": "Total project grant up to Rs. 45 Lakhs including Junior/Senior Research Fellow (JRF/SRF) monthly fellowship and contingency.",
            "min_qualification": "Ph.D. or MD/MS with active research track record",
            "max_age_limit": 65,
            "eligible_institutions": ["Universities", "IITs", "CSIR Institutes", "Medical Colleges", "ICMR Labs"],
            "raw_eligibility_text": "Faculty members and scientists with permanent employment in recognized Indian universities, medical colleges, and research institutes.",
            "full_text_content": "COUNCIL OF SCIENTIFIC AND INDUSTRIAL RESEARCH (CSIR)\nEXTRA MURAL RESEARCH (EMR) GRANTS 2026\nDomain: Biotechnology, Genomics, Drug Discovery, and Public Health Technologies.\nGrant Cap: Rs. 45 Lakhs for 3 years + JRF manpower at Rs. 37,000 per month + HRA.\nEligibility: Permanent faculty / research scientists. Closing date: 15-09-2026, extended to 30-09-2026.",
        },
        {
            "foa_id": "AICTE-RPS-2026-04",
            "title": "AICTE Research Promotion Scheme (RPS) for Technical Institutions",
            "agency": AgencyType.AICTE,
            "scheme_name": "Research Promotion Scheme (RPS)",
            "source_url": "https://www.aicte-india.org/schemes/rps-2026",
            "brief_summary": "Financial support to AICTE-approved engineering and polytechnic institutions to upgrade research infrastructure, undertake innovation in IoT, Robotics, EV technologies, and publish patents.",
            "thematic_areas": ["Electric Vehicles", "Robotics", "IoT", "VLSI Design", "Additive Manufacturing"],
            "domain": ResearchDomain.ELECTRONICS_ELECTRICAL,
            "thematic_thrust": "Next-Generation EV, IoT, and Embedded VLSI Systems",
            "target_beneficiary": BeneficiaryType.FACULTY,
            "open_date": date(2026, 8, 15),
            "closing_date": date(2026, 11, 15),
            "extended_closing_date": None,
            "max_amount_inr": 2500000.0,  # 25 Lakhs
            "overhead_pct": 5.0,
            "raw_budget_text": "Grant-in-aid up to Rs. 25 Lakhs for modernization of laboratory equipment and research consumables.",
            "min_qualification": "Master's or Ph.D. in Engineering / Technology",
            "max_age_limit": 55,
            "eligible_institutions": ["AICTE Approved Technical Institutions / Engineering Colleges"],
            "raw_eligibility_text": "Full-time faculty of AICTE approved technical institutions with minimum 5 years teaching/research experience.",
            "full_text_content": "ALL INDIA COUNCIL FOR TECHNICAL EDUCATION (AICTE)\nRESEARCH PROMOTION SCHEME (RPS) 2026-27\nObjective: Promoting research in technical institutes to create innovation and patents.\nMaximum Grant: Rs. 25 Lakhs over a 3-year timeline.\nEligibility: Regular faculty members in AICTE-approved engineering institutions.\nDeadline: 15 November 2026.",
        },
        {
            "foa_id": "NSP-PMSS-2026-05",
            "title": "NSP Prime Minister's Scholarship Scheme (PMSS) for Higher Technical Education",
            "agency": AgencyType.NSP,
            "scheme_name": "Prime Minister's Scholarship Scheme",
            "source_url": "https://scholarships.gov.in/schemes/pmss-2026",
            "brief_summary": "Financial assistance for meritorious undergraduate and postgraduate students enrolled in professional engineering, medical, and technology degree programs.",
            "thematic_areas": ["Scholarship", "Higher Education", "Engineering Degree", "Medical Degree"],
            "domain": ResearchDomain.INTERDISCIPLINARY,
            "thematic_thrust": "Merit-cum-Means Financial Support for Higher Technical Education",
            "target_beneficiary": BeneficiaryType.UG_PG_STUDENT,
            "open_date": date(2026, 7, 15),
            "closing_date": date(2026, 10, 31),
            "extended_closing_date": date(2026, 11, 30),
            "max_amount_inr": 36000.0,  # 36k per year
            "stipend_monthly_inr": 3000.0,
            "raw_budget_text": "Monthly scholarship of Rs. 3,000 for girls (Rs. 36,000/year) and Rs. 2,500 for boys (Rs. 30,000/year) disbursed directly to bank account.",
            "min_qualification": "Class 12th / Diploma passed with minimum 60% marks",
            "max_age_limit": 25,
            "eligible_institutions": ["Recognized Universities, Institutes offering AICTE/MCI/UGC approved technical courses"],
            "raw_eligibility_text": "Students admitted to 1st year of professional degree courses (B.Tech, MBBS, B.Pharm, MCA, MBA) with minimum 60% in 10+2 / Diploma.",
            "full_text_content": "NATIONAL SCHOLARSHIP PORTAL (NSP) - MINISTRY OF EDUCATION\nPRIME MINISTER'S SCHOLARSHIP SCHEME (PMSS) 2026\nTarget: Meritorious UG/PG students in professional and engineering courses.\nBenefit: Rs. 36,000 annually for female students and Rs. 30,000 for male students.\nDeadline: 31st October 2026 (Extended till 30th November 2026).",
        },
        {
            "foa_id": "ANRF-TARE-2026-06",
            "title": "ANRF Teachers Associateship for Research Excellence (TARE)",
            "agency": AgencyType.ANRF,
            "scheme_name": "TARE Associateship",
            "source_url": "https://anrfonline.in/schemes/tare-2026",
            "brief_summary": "Facilitates mobility of faculty working in state universities and colleges to carry out collaborative research at premier host institutions (IITs, IISc, IISERs, National Labs).",
            "thematic_areas": ["Collaborative Research", "Physical Sciences", "Chemical Sciences", "Faculty Mobility"],
            "domain": ResearchDomain.PHYSICAL_CHEMICAL_SCIENCES,
            "thematic_thrust": "Capacity Building & Premier Institute Collaborative Research",
            "target_beneficiary": BeneficiaryType.FACULTY,
            "open_date": date(2026, 8, 1),
            "closing_date": date(2026, 9, 30),
            "extended_closing_date": None,
            "max_amount_inr": 1500000.0,  # 15 Lakhs
            "stipend_monthly_inr": 15000.0,  # Research allowance
            "overhead_pct": 10.0,
            "raw_budget_text": "Research grant of Rs. 5 Lakhs per annum plus Rs. 15,000 per month research fellowship for 3 years.",
            "min_qualification": "Ph.D. in Science or Engineering/Technology",
            "max_age_limit": 45,
            "eligible_institutions": ["State Universities, Colleges, and Private Academic Institutions"],
            "raw_eligibility_text": "Faculty from State Universities and Colleges aged up to 45 years who wish to collaborate with mentors in CFTIs / IISc / IITs.",
            "full_text_content": "ANRF TEACHERS ASSOCIATESHIP FOR RESEARCH EXCELLENCE (TARE) 2026\nObjective: Tap untapped research potential of state universities and colleges.\nGrant: Rs. 5 Lakhs/year grant + Rs. 15,000/month research allowance.\nEligibility: Regular faculty with Ph.D., age <= 45 years. Deadline: 30 Sept 2026.",
        },
        {
            "foa_id": "DBT-BIG-2026-07",
            "title": "DBT-BIRAC Biotechnology Ignition Grant (BIG) for MedTech & Bio-Innovation",
            "agency": AgencyType.DBT,
            "scheme_name": "Biotechnology Ignition Grant",
            "source_url": "https://dbtindia.gov.in/schemes/birac-big-2026",
            "brief_summary": "Ignition grant for innovative biotech, healthcare, agricultural, and biomedical ideas to establish proof-of-concept and foster startup creation.",
            "thematic_areas": ["Bio-Innovation", "MedTech", "Biomedical Devices", "Synthetic Biology", "Agritech"],
            "domain": ResearchDomain.BIOTECHNOLOGY_HEALTHCARE,
            "thematic_thrust": "Proof-of-Concept MedTech Innovation & Biotech Startups",
            "target_beneficiary": BeneficiaryType.STARTUP_INDUSTRY,
            "open_date": date(2026, 7, 1),
            "closing_date": date(2026, 8, 31),
            "extended_closing_date": date(2026, 9, 15),
            "max_amount_inr": 5000000.0,  # 50 Lakhs
            "overhead_pct": 0.0,
            "raw_budget_text": "Up to Rs. 50 Lakhs grant-in-aid for 18 months to reach Proof of Concept (PoC).",
            "min_qualification": "Graduate in Biotech, Life Sciences, Medicine, or Engineering",
            "max_age_limit": 50,
            "eligible_institutions": ["Startups (< 5 yrs old), Individual Innovators, Incubatees, Researchers"],
            "raw_eligibility_text": "Indian individuals, research scholars, faculty entrepreneurs, or registered Indian startups with <= 5 years incorporation.",
            "full_text_content": "DEPARTMENT OF BIOTECHNOLOGY (DBT) & BIRAC\nBIOTECHNOLOGY IGNITION GRANT (BIG) CALL 28\nObjective: Enable commercialization of bio-innovations and support early-stage MedTech startups.\nFunding: Grant of up to Rs. 50,00,000 (50 Lakhs) for 18 months.\nClosing Date: 31st August 2026 (Extended to 15th September 2026).",
        },
        {
            "foa_id": "DST-WISE-2026-08",
            "title": "DST WISE-KIRAN Postdoctoral Fellowship for Women in Science",
            "agency": AgencyType.DST,
            "scheme_name": "WISE-PDF Scheme",
            "source_url": "https://dst.gov.in/call-for-proposals/wise-pdf-2026",
            "brief_summary": "Fellowship opportunity for unemployed or career-break women scientists holding a Ph.D. to re-enter frontier research in science, mathematics, and engineering.",
            "thematic_areas": ["Women in Science", "Postdoctoral Fellowship", "Chemical Sciences", "Environmental Studies"],
            "domain": ResearchDomain.PHYSICAL_CHEMICAL_SCIENCES,
            "thematic_thrust": "Re-entry and Fellowship for Women Researchers with Ph.D.",
            "target_beneficiary": BeneficiaryType.PHD_POSTDOC,
            "open_date": date(2026, 6, 1),
            "closing_date": date(2026, 12, 31),
            "extended_closing_date": None,
            "is_rolling": True,
            "max_amount_inr": 2200000.0,  # 22 Lakhs
            "stipend_monthly_inr": 55000.0,  # Monthly PDF fellowship
            "overhead_pct": 8.0,
            "raw_budget_text": "Monthly fellowship of Rs. 55,000 + HRA + Rs. 2,00,000 annual research grant for 3 years.",
            "min_qualification": "Ph.D. in Basic or Applied Sciences / Engineering",
            "max_age_limit": 45,
            "eligible_institutions": ["Any recognized Indian University / National Institute / Research Lab"],
            "raw_eligibility_text": "Unemployed women scientists and engineers aged between 27 to 45 years with a Ph.D. degree.",
            "full_text_content": "DST WOMEN IN SCIENCE AND ENGINEERING (WISE) POSTDOCTORAL FELLOWSHIP\nTarget: Ph.D. women scientists seeking independent research opportunities.\nFellowship: Rs. 55,000/month + research grant. Rolling call open until 31 December 2026.",
        },
    ]

    opportunities = []
    for item in raw_data:
        text_payload = item["full_text_content"]
        content_hash = hashlib.sha256(text_payload.encode("utf-8")).hexdigest()

        foa = FundingOpportunity(
            foa_id=item["foa_id"],
            title=item["title"],
            agency=item["agency"],
            scheme_name=item["scheme_name"],
            source_url=item["source_url"],
            pdf_download_url=f"{item['source_url']}/guidelines.pdf",
            raw_document_hash=content_hash,
            brief_summary=item["brief_summary"],
            thematic_areas=item["thematic_areas"],
            ontology_tags=[
                AcademicOntologyTag(
                    domain=item["domain"],
                    thematic_thrust=item["thematic_thrust"],
                    target_beneficiary=item["target_beneficiary"],
                    confidence=0.95,
                )
            ],
            eligibility=EligibilityCriteria(
                target_beneficiaries=[item["target_beneficiary"]],
                min_qualification=item.get("min_qualification"),
                max_age_limit=item.get("max_age_limit"),
                eligible_institutions=item.get("eligible_institutions", []),
                raw_eligibility_text=item.get("raw_eligibility_text"),
            ),
            deadlines=Deadlines(
                open_date=item.get("open_date"),
                closing_date=item.get("closing_date"),
                extended_closing_date=item.get("extended_closing_date"),
                is_rolling=item.get("is_rolling", False),
                raw_deadline_text=f"Closing: {item.get('closing_date')}",
            ),
            financials=FinancialCeiling(
                max_amount_inr=item.get("max_amount_inr"),
                stipend_monthly_inr=item.get("stipend_monthly_inr"),
                institutional_overhead_pct=item.get("overhead_pct"),
                raw_budget_text=item.get("raw_budget_text"),
            ),
            full_text_content=item["full_text_content"],
            is_ocr_extracted=False,
            ingested_at=datetime.now(timezone.utc),
        )
        opportunities.append(foa)

    return opportunities
