"""RFC 5545 iCalendar (.ics) Generator for Grant Deadlines."""
from datetime import datetime, time, timedelta, timezone
import logging
from typing import Optional
try:
    from zoneinfo import ZoneInfo
except ImportError:
    ZoneInfo = None
from icalendar import Alarm, Calendar, Event

from src.schemas.foa import FundingOpportunity

logger = logging.getLogger("MadadgaarAI.Matcher.Calendar")


class CalendarSyncGenerator:
    def __init__(self, tz_name: str = "Asia/Kolkata"):
        if ZoneInfo:
            try:
                self.tz = ZoneInfo(tz_name)
            except Exception:
                self.tz = timezone.utc
        else:
            self.tz = timezone.utc

    def generate_ics_for_foa(self, foa: FundingOpportunity) -> bytes:
        """Generates standard .ics calendar bytes for a given funding opportunity."""
        cal = Calendar()
        cal.add("prodid", "-//MadadgaarAI Funding Intelligence//jklu.edu.in//EN")
        cal.add("version", "2.0")
        cal.add("calscale", "GREGORIAN")
        cal.add("x-wr-calname", f"MadadgaarAI Deadline: {foa.foa_id}")

        effective_deadline = foa.deadlines.effective_deadline
        if not effective_deadline:
            # If rolling, set an informative recurring calendar event
            event = Event()
            event.add("summary", f"[Rolling Call] {foa.title} ({foa.agency.value})")
            event.add("description", f"Rolling call. Check details at: {foa.source_url}\n\nSummary:\n{foa.brief_summary}")
            event.add("dtstart", datetime.now().date())
            event.add("dtend", datetime.now().date())
            event.add("uid", f"{foa.foa_id}-rolling@madadgaarai.ai")
            cal.add_component(event)
            return cal.to_ical()

        # Closing Deadline Event
        deadline_dt = datetime.combine(effective_deadline, time(17, 0))  # 5:00 PM IST standard submission close
        deadline_dt = deadline_dt.replace(tzinfo=self.tz)

        event = Event()
        event.add("summary", f"🚨 Grant Deadline: {foa.title} ({foa.agency.value})")
        description_text = (
            f"Funding Opportunity: {foa.title}\n"
            f"Agency: {foa.agency.value}\n"
            f"Scheme: {foa.scheme_name or 'N/A'}\n"
            f"Max Grant: ₹ {foa.financials.max_amount_inr:,.2f}\n" if foa.financials.max_amount_inr else ""
            f"Portal URL: {foa.source_url}\n\n"
            f"Summary:\n{foa.brief_summary}\n\n"
            f"Auto-generated by MadadgaarAI"
        )
        event.add("description", description_text)
        event.add("dtstart", deadline_dt)
        event.add("dtend", deadline_dt)
        event.add("dtstamp", datetime.now(self.tz))
        event.add("uid", f"{foa.foa_id}-deadline@madadgaarai.ai")
        event.add("url", foa.source_url)
        event.add("status", "CONFIRMED")
        event.add("categories", ["GRANT_DEADLINE", "RESEARCH", foa.agency.value])

        # 7-day reminder alarm
        alarm_7d = Alarm()
        alarm_7d.add("action", "DISPLAY")
        alarm_7d.add("description", f"Reminder: 7 days until {foa.foa_id} deadline!")
        alarm_7d.add("trigger", timedelta(days=-7))
        event.add_component(alarm_7d)

        # 1-day reminder alarm
        alarm_1d = Alarm()
        alarm_1d.add("action", "DISPLAY")
        alarm_1d.add("description", f"URGENT: 24 hours left to submit {foa.foa_id} proposal!")
        alarm_1d.add("trigger", timedelta(days=-1))
        event.add_component(alarm_1d)

        cal.add_component(event)
        return cal.to_ical()
